services:
  xray:
    image: teddysun/xray
    container_name: xray
    volumes:
      - ./compose-data/xray/config:/etc/xray
    ports:
      - "10000:10000"
    restart: unless-stopped

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./compose-data/nginx/conf.d:/etc/nginx/conf.d
      - ./compose-data/nginx/logs:/var/log/nginx
      - ./compose-data/certbot/conf:/etc/letsencrypt
      - ./compose-data/certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    depends_on:
      - certbot
      - xray

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./compose-data/certbot/conf:/etc/letsencrypt
      - ./compose-data/certbot/www:/var/www/certbot
    entrypoint: /bin/sh -c 'trap exit TERM; while :; do sleep 6h & wait $${!}; certbot renew; done'